name: test-java
on: 
    push:
        branches: 
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Comprobar repo
              uses: actions/checkout@v4
            
            - name: configurar JDK
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'temurin'
            
            - name: Compilar y ejecutar pruebas
              run: mvn test